"""GitHub agent — creates a repo, commits generated files, and opens an initial PR.

Uses PyGithub with GITHUB_PAT from config. Derives the repo name from the
project brief (lowercase, hyphen-separated, max 40 chars). Appends a timestamp
if a repo with that name already exists to avoid collisions.

All generated files are committed to a ``scaffold/initial`` branch so that an
initial PR against ``main`` can be opened immediately after repo creation.
"""

from __future__ import annotations

import re
import time
from pathlib import Path
from typing import Any

import github as gh

from config import GITHUB_PAT
from scripts.logger import get_logger

logger = get_logger(__name__)


def _repo_slug(project_brief: str) -> str:
    """Derive a hyphen-separated repo name slug from the project brief.

    Args:
        project_brief: Plain-English project description.

    Returns:
        Lowercase, hyphen-separated slug of at most 40 characters.
    """
    slug = re.sub(r"[^a-z0-9]+", "-", project_brief.lower().strip()).strip("-")
    return slug[:40] or "project"


def run_github(
    project_brief: str,
    generated_file_paths: list[str],
    devops_config_paths: list[str],
) -> str:
    """Create a GitHub repo, commit all generated files, and open an initial PR.

    Args:
        project_brief: Original plain-English project description. Used to
            derive the repo name slug and as the repo description.
        generated_file_paths: Absolute paths to source files written by the
            Coder agent.
        devops_config_paths: Absolute paths to infrastructure files written by
            the DevOps agent (Dockerfile, ci.yml, etc.).

    Returns:
        The HTML URL of the newly created GitHub repository.

    Raises:
        gh.GithubException: If any GitHub API call fails.
        OSError: If a file listed in the paths cannot be read from disk.
    """
    client = gh.Github(auth=gh.Auth.Token(GITHUB_PAT))
    user: Any = client.get_user()

    slug = _repo_slug(project_brief)

    try:
        user.get_repo(slug)
        slug = f"{slug}-{int(time.time())}"
        logger.info("run_github: repo name collision — using slug %s", slug)
    except gh.UnknownObjectException:
        pass

    logger.info("run_github: creating repo %s/%s", user.login, slug)
    repo = user.create_repo(
        slug,
        description=project_brief[:255],
        private=True,
        auto_init=True,
    )

    main_ref = repo.get_git_ref("heads/main")
    main_sha = main_ref.object.sha

    repo.create_git_ref(ref="refs/heads/scaffold/initial", sha=main_sha)
    logger.info("run_github: created branch scaffold/initial from %s", main_sha[:7])

    all_paths = list(generated_file_paths) + list(devops_config_paths)

    output_prefix = _find_output_prefix(all_paths)

    committed = 0
    for abs_path in all_paths:
        path_obj = Path(abs_path)
        if not path_obj.exists():
            logger.warning("run_github: skipping missing file %s", abs_path)
            continue

        rel_path = _relative_path(abs_path, output_prefix)
        content = path_obj.read_bytes()

        try:
            repo.create_file(
                path=rel_path,
                message=f"scaffold: add {rel_path}",
                content=content,
                branch="scaffold/initial",
            )
            committed += 1
            logger.info("run_github: committed %s", rel_path)
        except gh.GithubException as exc:
            logger.error("run_github: failed to commit %s: %s", rel_path, exc)
            raise

    logger.info("run_github: committed %d files to scaffold/initial", committed)

    pr = repo.create_pull(
        title="Initial scaffold from AI pipeline",
        body=(
            "This PR contains the full AI-generated scaffold for the project.\n\n"
            "Generated by the multi-agent development pipeline."
        ),
        head="scaffold/initial",
        base="main",
    )
    logger.info("run_github: opened PR #%d — %s", pr.number, pr.html_url)

    return repo.html_url


def _find_output_prefix(paths: list[str]) -> str:
    """Find the output/code/ prefix common to all generated paths.

    Matches the new run_dir structure: output/<run_id>/code/. Stripping this
    prefix gives repo-relative paths so files commit at the repo root.

    Args:
        paths: List of absolute file paths.

    Returns:
        The common output prefix string, or empty string if not determinable.
    """
    for p in paths:
        match = re.match(r"(.*?/output/[^/]+/code/)", p)
        if match:
            return match.group(1)
    return ""


def _relative_path(abs_path: str, prefix: str) -> str:
    """Strip the output prefix to get a repo-relative path.

    Args:
        abs_path: Absolute path to a generated file.
        prefix: The /output/{project_name}/ prefix to strip.

    Returns:
        Repo-relative path string (forward slashes, no leading slash).
    """
    if prefix and abs_path.startswith(prefix):
        return abs_path[len(prefix) :]
    return Path(abs_path).name
